#### NOAA Storm Database - worst cases

Analysis of the NOAA Storm Database, in order to determine what are the worst natural catastrophic events, both in terms of public health and in economic impact. 

The U.S. National Oceanic and Atmospheric Administration’s (NOAA) storm database tracks characteristics of major storms and weather events in the United States, including when and where they occur, as well as estimates of any fatalities, injuries, and property damage.

The database currently contains data from January 1950 to January 2017, as entered by NOAA’s National Weather Service (NWS).

Done in R programming language.

[Shinny Dashboard - R](https://erickfis.shinyapps.io/noaa_storm_db_-_economic_losses_-_nvd3/)

***

#### Management Dashboard for BI

A complete live BI Dashboard that allows managers and stakeholders to quickly track key business metrics (KPIs) and then to take data driven decisions. This app automatically retrieves data from the SQL server so it is always displaying updated information.

Built using Python + Flask + AWS Elastic BeanStalk.

under maintennance 

[BI Live Dashboard](http://gerencial.sa-east-1.elasticbeanstalk.com/)